"""State machine package: registry (pure data) + validator (pure functions)."""

from pinner.statemachine.registry import (
    EVENTS,
    INGEST_TRANSITIONS,
    PUBLICATION_TRANSITIONS,
    STATE_ROLES,
    TRANSITIONS,
    Kind,
    Machine,
    PinState,
    ProductState,
    Role,
    Transition,
)
from pinner.statemachine.validator import (
    AmbiguousTransitionError,
    IllegalTransitionError,
    can_transition,
    check_invariants,
    claimable_states,
    legal_events,
    state_role,
    sweep_target,
    terminal_states,
    transition_for,
    transitions_from,
    working_states,
)

__all__ = [
    "EVENTS",
    "INGEST_TRANSITIONS",
    "PUBLICATION_TRANSITIONS",
    "STATE_ROLES",
    "TRANSITIONS",
    "AmbiguousTransitionError",
    "IllegalTransitionError",
    "Kind",
    "Machine",
    "PinState",
    "ProductState",
    "Role",
    "Transition",
    "can_transition",
    "check_invariants",
    "claimable_states",
    "legal_events",
    "state_role",
    "sweep_target",
    "terminal_states",
    "transition_for",
    "transitions_from",
    "working_states",
]
